[versions]
javaAnnotations = "26.0.2-1"
lombok = "1.18.42"
junit-bom = "6.0.0"
junit-jupiter = "6.0.0"
junit-platform = "6.0.0"

[libraries]
javaAnnotations = { module = "org.jetbrains:annotations", version.ref = "javaAnnotations" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }